apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  selector:
    matchLabels:
      app: eureka-server
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: eureka:0.1
        ports:
        - containerPort: 8761
---
# https://kubernetes.io/docs/concepts/s...  
kind: Service
apiVersion: v1
metadata:
  name: eureka-server-service
spec:
  type: NodePort
  selector:
    app: eureka-server
  ports:
  - protocol: TCP
    port: 8761
    targetPort: 8761
    nodePort: 30000
  